name: Build and Push Docker Image to GHCR and Docker Hub

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to both registries
        run: |
          IMAGE_NAME=myusername/hugtest
          GHCR_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hugtest
          
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:latest \
            -t $GHCR_IMAGE_NAME:latest \
            --push .
